deploy:
  provider: bluemixcloudfoundry
  skip_cleanup: true
  manifest: manifest.yml
  username: $BLUEMIX_USER
  password: $BLUEMIX_PASSWORD
  organization: $BLUEMIX_ORGANIZATION
  space: $BLUEMIX_SPACE
  on:
    branch: stable